/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 leads.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/leads.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[2.05, 2.03, -2.02]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[2.032, 1.018, 2.045]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[-2.045, 0.018, 2.032]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[-2.05, -0.97, -2.02]} />
    </group>
  )
}

useGLTF.preload('/leads.glb')
